spring:
  application:
    name: hello-interview

  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migrations
    validate-on-migrate: true

server:
  servlet:
    context-path: /api  # All endpoints will now start with /api

logging:
  level:
    com.hello.interview: DEBUG  # Custom package logging
    org.springframework: WARN
    org.springframework.security: WARN
    org.hibernate: WARN

